# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectrum_analyzer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget
import serial
import serial.tools.list_ports
import sys
import numpy as np

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.traces =  dict()
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 5)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setAccessibleName("")
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.comboBox2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox2.setCurrentText("")
        self.comboBox2.setObjectName("comboBox2")
        self.gridLayout.addWidget(self.comboBox2, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.load_serial_comports()
        self.baudrate_selection()
        self.pushButton.clicked.connect(self.plot)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spectrum Analyzer"))
        self.label.setText(_translate("MainWindow", "COM PORT"))
        self.label_2.setText(_translate("MainWindow", "Baudrate"))
        self.pushButton.setText(_translate("MainWindow", "Connect"))

    def load_serial_comports(self):
        ports = serial.tools.list_ports.comports()
        for port in ports:
            self.comboBox.addItem(f"{port.device}")

    def baudrate_selection(self):
        baudrates = ["9600","19200","38400","57600","115200"]
        for baud in baudrates:
            self.comboBox2.addItem(f"{baud}")

    def comport_connection(self):
        global ser
        port = self.comboBox.currentText()
        baud = self.comboBox2.currentText()
        if port and baud:
            print(f"{port} ile {baud} secilmistir")
            ser = serial.Serial(port,baudrate=int(baud),timeout=1)

    def update(self):
        while ser.is_open:
            data_bytes = ser.readline()
            decoded_bytes = data_bytes.decode("ascii").strip('\r\n')
            data_value = [int(x) for x in range(decoded_bytes.split('|'))]
            
            print(data_value[1:])


    def start(self):
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())

    def animation(self):
        timer =  QtCore.QTimer()
        timer.timeout.connect(self.update)
        timer.start(30)
        self.start()

if __name__ == "__main__":
    u = Ui_MainWindow()
    u.animation()
